- name: Ansible job create
  hosts: localhost
  tasks:
    - name: create jenkins jobs
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: test2
        password: admin
        url: http://172.31.87.136:8080
        user: admin