- name: Ansible job create
  hosts: localhost
  vars:
    jenkins_url: http://172.31.87.136:8080
    jenkins_user: admin
    jenkins_password: "{{ lookup('aws_ssm', 'jenkins_password', region='us-east-1' ) }}"
  tasks:
    - name: create jenkins jobs frontend
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: frontend
        password: "{{jenkins_password}}"
        url: "{{jenkins_url}}"
        user: "{{jenkins_user}}"
      vars:
        repo_name: frontend
        auto_trigger: "true"
        
    - name: create jenkins jobs backend
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: backend
        password: "{{jenkins_password}}"
        url: http://172.31.87.136:8080
        user: "{{jenkins_user}}"
      vars:
        repo_name: backend
        auto_trigger: "true"
     
    - name: Create Jenkins Job - Schema Load
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: backend
        password: "{{jenkins_password}}"
        url: http://172.31.87.136:8080
        user: "{{jenkins_user}}"
      vars:
        repo_name: expense-schema-load
        auto_trigger: "true"
        
    - name: create jenkins jobs Expense Parameters
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: expense-parameters
        password: "{{jenkins_password}}"
        url: http://172.31.87.136:8080
        user: "{{jenkins_user}}"
      vars:
        repo_name: parameter-store   
        auto_trigger: "false"

        
    - name: create jenkins jobs Expense Terraform
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: expense-terraform
        password: "{{jenkins_password}}"
        url: http://172.31.87.136:8080
        user: "{{jenkins_user}}"
      vars:
        repo_name: expense-terraform
        auto_trigger: "false"
 
        
    - name: Create Jenkins Job - Mutable Deployment
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: mutable-deployment
        password: "{{jenkins_password}}"
        url: http://172.31.87.136:8080
        user: "{{jenkins_user}}"
      vars:
        repo_name: infra-ansible
        auto_trigger: "false"
        
        
    - name: Create Jenkins Job - RoboShop Terraform
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: roboshop-terraform
        password: "{{jenkins_password}}"
        url: http://172.31.94.64:8080
        user: "{{jenkins_user}}"
      vars:
        repo_name: roboshop-terraform
        auto_trigger: "false"
        file_name: Jenkinsfile
